### ISSUE TITLE
Does ignore in local_resource support glob pattern?

### ISSUE THREAD

**Issue by DatXN** [tilt-dev/tilt#3740]
Hi all, 
I follow this example `https://docs.tilt.dev/example_csharp.html` and use local resource

This is the project structure:

> **Working dir**
> 
> ```
> .
> ├── devops
> │   ├── k8s
> │   │	  ├── Tiltfile2
> │   │	  └── out
> ├── project1
> │   ├── bin
> │   ├── obj
> │   └── ...
> ├── project2
> │   ├── bin
> │   ├── obj
> │   └── ...
> ├── ...
> ├── Tiltfile1
> ├── .dockerignore
> └── ...
> ```

This is the value of my Tiltfile2:

```
local_resource(
    'publish_local_svc_order_api',
    'dotnet publish ... -c Release -o out',
    deps=[
        '../../../'
        ],
    ignore=[
        './../../**/obj',
        '../../../**/bin'
    ]
)

```

This is the value of my Tiltfile1:
```
local_resource(
    'publish_local_svc_order_api',
    'dotnet publish ... -c Release -o out',
    deps=[
        '.'
        ],
    ignore=[
        '**/obj',
        '**/bin'
    ]
)

```
However, when the local build is running the file in **/bin and **/obj is changed and causing the local_resource run into a loop.

So my questions are:
1. **Does ignore support glob pattern? or is this a bug?**

2. I know .dockerignore doesn't allow ignore with pattern coming from a child folder (   './../../**/obj' ) but can Titl.dev support this? It will very helpful if I can put the Tiltfile inside a child folder (for organization purpose).

3. Or do we have the feature to set the "working dir/context" of Tiltfile execution instead of always where the Tiltfile is located.

Thanks, DatXN.

**Comment by victorwuky** [comment]
@nicks : Made this an `enhancement` issue, as a feature request. Let me know if that's incorrect.

**Comment by nicks** [comment]
Ya, to answer your question -
1) local_resource uses the same interpreter as dockerignore, so it doesn't support **. Most build systems, AFAIK, don't support this, or put strong limits on how they support it, because double-star globs can lead to some extreme performance characteristics if you're not careful. So I think it's not likely we'll be able to support this, but am happy to leave the issue open.
2) I'm actually surprised that the `..` doesn't work! I think this is a bug. Let me poke at this a bit and try to get more detail.
3) There's no feature for changing the working dir, but there ARE good API calls for working with paths (see https://docs.tilt.dev/api.html#modules.os.path.abspath)

**Comment by DatXN** [comment]
Hi,

Thank you for your response.

1. For 1, for what I understand, the Titlefile hot-reload/auto trigger will ignore the same as .dockerignore. And my dockerignore actually have '**/obj'. And your tilt up work perfectly fine. So I think in this case, it actually work with '**/obj', just that I use it in ignore of local_resource, it doesn't work. That's what confuse me, if you actually be able to support ignore '**/obj' in normal case, why not this case?



2. For 2, I would want to give more detail on this: By doesn't work, I mean when I use the `Tiltfile2` (which inside a child folder )of Work dir, and the code below doesn't work:
```

ignore=[
        './../../**/obj',
        '../../../**/bin'
    ]
```
3. This actually a different issue, this feature will nice to have but not so important. Since we dont want to do this in every file: 

```
#DEPLOY
k8s_yaml("../../../../devops/kubernetes/Development/remote_minikube/dx-next-services-demo-demoapi-svc-pod-depl.yml")
k8s_yaml("../../../../devops/kubernetes/Development/remote_minikube/dx-next-services-svcorder-orderapi-svc-depl.yml")
k8s_yaml("../../../../devops/kubernetes/Development/remote_minikube/services.yml")
```
Btw, 
This project is great and super helpful for someone who want a efficiency development workflow.
I great appreciation and thank to everyone contributed to make this great tool!

Thanks, DatXN.

**Comment by landism** [comment]
> local_resource uses the same interpreter as dockerignore, so it doesn't support **.

Both tilt and dockerignore support `**` in ignores. https://docs.docker.com/engine/reference/builder/:
> Beyond Go’s filepath.Match rules, Docker also supports a special wildcard string ** that matches any number of directories (including zero). For example, **/*.go will exclude all files that end with .go that are found in all directories, including the root of the build context.

Maybe you're thinking of the fact that docker, and thus tilt, have issues with exceptions (`!`) and wildcards: https://github.com/moby/moby/issues/30018, and so Tilt doesn't support wildcards in positive match cases (e.g., `only`, `deps`)?

> the code below doesn't work
```
ignore=[
        './../../**/obj',
        '../../../**/bin'
    ]
```

Is it intentional that the `obj` line has one fewer leading `.` than the `bin` line? I would expect them to be the same, and that would explain the problem.

**Comment by DatXN** [comment]
@landism No, that's my mistake. But just in this comment. When I use it in my project, the ignore still doesn't work.

**Comment by nicks** [comment]
Ya, I misread something, @landism is right, this does support ** double-star globs, it's just the '../' bit that's not supported properly.

**Comment by nicks** [comment]
This should be fixed in tilt v0.17.4 !

**Comment by DatXN** [comment]
Tried v0.17.4.

With following setting:
```

local_resource(
    'publish_local_svc_order_api',
    'dotnet publish ../../../../src/Services/SvcOrder/SvcOrder.Presentation/SvcOrder.API/Dx.Next.Services.SvcOrder.OrderAPI/Dx.Next.Services.SvcOrder.SvcOrderAPI.csproj -c Debug -o ../../../out/Dx.Next.Services.SvcOrder.OrderAPI',
    deps=['../../../../src/'],
    ignore=[
        '../../../../src/**/obj',
        '../../../../src/**/bin',
        '../../../../src/**/out'
    ]
)

local_resource(
    'publish_local_svc_demo_api',
    'dotnet publish ../../../../src/Services/Demo/Demo.Presentation/Demo.API/Dx.Next.Services.Demo.DemoAPI/Dx.Next.Services.Demo.DemoAPI.csproj -c Debug -o ../../../out/Dx.Next.Services.Demo.DemoAPI',
    deps=['../../../../src/'],
    ignore=[
        '../../../../src/**/obj',
        '../../../../src/**/bin',
        '../../../../src/**/out'
    ]
)
```


Still not work. (Tilt.dev still says that there is file changes in .../src ... /obj/ ...)

Am I missing something?

**Comment by nicks** [comment]
Hi @DatXN ! 

I just tried this in my test sandbox and it seemed to work ok for me.

https://github.com/tilt-dev/tilt-example-csharp/blob/nicks/issue3740/3-live-update/Tiltfile#L19

I confirmed that in the 3-live-update directory:
1) `touch hello-tilt/Startup.cs` re-runs `build`
2) `touch hello-tilt/obj/project.assets.json` is ignored

Does that match what you're seeing? Or is there something special about your example that I'm missing?

One thing I noticed is that your example outputs to 
 ../../../out/Dx.Next.Services.SvcOrder.OrderAPI
but the ignore parameter specifies
../../../../src/**/out
so maybe it needs to be `../../../out`?

**Comment by DatXN** [comment]
Tried your code, it not work on my machine.

This file keep shows as changed

![image](https://user-images.githubusercontent.com/5478040/92681397-b570e300-f357-11ea-9464-276411408586.png)


Mac OS

Tilt version 0.17.4

![image](https://user-images.githubusercontent.com/5478040/92681433-cd486700-f357-11ea-94bf-20be97842873.png)

**Comment by nicks** [comment]
ok, i see the problem.

you can work around it for now by doing

../../../../src/**/out/**

there's a subtle issue with how docker's file matching library interops with our path matching library. Basically, dockerignore operates on file tree walks (where it's also running the match on all parent dirs) whereas our matcher has to operate on individual files (where it's not running the match on all parent dirs)

**Comment by DatXN** [comment]
Hi, I tried your work around and look like it stops the loop issue.

But I do notice that during the local build for multiple project, it still show the change from obj folder inside the solution.

**Comment by nicks** [comment]
ya, i think i can distill this into a docker bug, filing it upstream

**Comment by nicks** [comment]
here's the upstream docker issue: https://github.com/moby/moby/issues/41433

**Comment by nicks** [comment]
(the way that this manifests in tilt is more complicated than the description there, but that description is a simplified case that covers the essence of it)

**Comment by nicks** [comment]
is it possible to not use the `**` glob in your ignore? looking at how it's implemented in docker, i'm not sure I'd rely on it, the implementation has...a couple of different issues

**Comment by nicks** [comment]
the fix for this should be out in v0.17.5!
